apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    app: udagram-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-user
  template:
    metadata:
      labels:
        app: udagram-user
    spec:
      containers:
      - name: udagram-api-user
        image: huannguyenngoc/udagram-api-user:v1
        ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /user-health
          port: 8080